# Generated by Django 2.2 on 2019-04-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techreviewapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingtype', models.CharField(max_length=255)),
                ('meetingtitle', models.CharField(max_length=255)),
                ('meetingdate', models.DateField()),
                ('posteddate', models.DateField()),
                ('experiencelevel', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'techmeetings',
                'db_table': 'techmeeting',
            },
        ),
    ]
